# Generated by Django 3.2.15 on 2022-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('feedback', models.CharField(max_length=50)),
                ('reply', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
