# Generated by Django 3.2.15 on 2022-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('card_number', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=30)),
                ('cvv', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'payment',
                'managed': False,
            },
        ),
    ]
