# Generated by Django 3.2.15 on 2022-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=25)),
                ('product_name', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('expdate', models.DateField()),
                ('stock', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
    ]
