# Generated by Django 3.2.15 on 2022-10-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=30)),
                ('foodchart', models.CharField(max_length=50)),
                ('exercise', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'training_plan',
                'managed': False,
            },
        ),
    ]
